- src/CodeItem.re
If not
```
[@genFlow]
let make = (children) => {
...component,
render: _self => <Text style=Styles.largeTitle> ...children </Text>,
};
```
would make flow complain when passing children from JS, because outputted flow props doesn't have optional children.
This only happens when `children` is the only prop.
> We should add optional children here

- README.md
Hopefully helps other people that are also wondering why `export BS_CMT_POST_PROCESS_CMD="$GENFLOW_REPO/lib/bs/native/genflow.native` isn't working.
@cristianoc I think a newcomer could probably give up, as there is no feedback from genFlow when `setProjectRoot` is missing. Should it show an error if that's the case?
> Bring back setProjectRoot reference to the readme

- .dockerignore
- Dockerfile
- README.md
I needed a way to build Linux built artifacts locally.
These instructions make it easy to do.... also it adds some notes how to tar up those `genflow.native` files correctly.
In the future, I will try to automate this (together with automatic release publishing), as stated in #26
> Add Linux build mechanics

- appveyor.yml
- package.json
This will make appveyor build a Windows compatible binary.
You need to register on app-veyor and add the genType repository... as soon as it's added it should do a successful windows build
> Add appveyor support

- README.md
Fixes #61.
Adds a note to the readme about exposing values from polymorphic types with hidden type variables.
> Add note about exposing values from polymorphic types with hidden type variables

- examples/run_bsb.js
- examples/typescript-react-example/clean.js
- scripts/run_integration_tests.js
Enables `git diff` which checks for regressions after cleaning & building all examples.
**Still in progress:**
> Fix git diffing

- examples/typescript-react-example/bsconfig.json
- examples/typescript-react-example/src/shims/ReactShim.shim.ts
Add ReactShim and update bsconfig in typescript example.
Resolve `Cannot find module './ReasonReact.gen'` error.
https://github.com/cristianoc/genType/issues/135#issuecomment-461609145
> Add ReactShim and update bsconfig in typescript example.

- Changes.md
- examples/commonjs-react-example/src/Hooks.gen.js
- examples/flow-react-example/src/Hooks.gen.js
- src/EmitJs.re
- src/EmitType.re
- src/EmitType.rei
If a function component is type annotated, then it is not checked by Flow.
Work around this issue by defining an auxiliary wrapper function just to call typeof() on it. The wrapper function is not type annotated directly, but its parameters and return are.
This makes Flow type check function components.
> Work around issue with Flow and function components.

- Changes.md
- examples/typescript-react-example/src/Opaque.bs.js
- examples/typescript-react-example/src/Opaque.gen.tsx
- examples/typescript-react-example/src/Opaque.re
- src/Converter.re
- src/EmitJs.re
- src/EmitType.re
- src/GenTypeCommon.re
- src/TranslateTypeExprFromTypes.re
- src/TypeVars.re
Revisit type normalization so inlining goes deep into types.
Remove the use of opaque types during normalization. Using opaque types for unknown types was not compatible with inlining (e.g. the type definition discovered later).
> Inline types

- Changes.md
- README.md
- examples/typescript-react-example/src/Hooks.bs.js
- examples/typescript-react-example/src/Hooks.gen.tsx
- examples/typescript-react-example/src/Hooks.re
- src/Runtime.re
- src/Runtime.rei
- src/TranslateCoreType.re
- src/TranslateTypeExprFromTypes.re
This gives unified support for renaming on normal functions with named arguments, and function components.
Related: https://github.com/cristianoc/genType/issues/194.
> Apply object field mangling convention to named arguments in functions.

- Changes.md
- examples/flow-react-example/src/Hooks.gen.js
- examples/flow-react-example/src/Types.gen.js
- examples/typescript-react-example/src/Hooks.gen.tsx
- examples/typescript-react-example/src/Uncurried.gen.tsx
- examples/untyped-react-example/src/App.gen.js
- examples/untyped-react-example/src/main.js
- src/Converter.re
Don't generate conversion for callbacks of type unit => ..., as it's unnecessary from bucklescript 5.
Before bucklescript version 5, passing a function with arity 0 from JS would give a runtime error,
so a conversion was used to avoid this, adding runtime cost.
> Don't generate conversion for callbacks of type unit => ..., as it's unnecessary from bucklescript 5.

- Changes.md
- examples/flow-react-example/src/Hooks.gen.js
- examples/flow-react-example/src/Hooks.re
- examples/typescript-react-example/src/Hooks.gen.tsx
- examples/typescript-react-example/src/Hooks.re
- package-lock.json
- package.json
- src/EmitType.re
- src/EmitType.rei
- src/TranslateTypeExprFromTypes.re
- src/Version.re
Fixes https://github.com/cristianoc/genType/issues/271
> Make React.Ref more permissive: `{contents: null | T}`

- .ci/build-platform.yml
- .ci/utils/cache.yml
- azure-pipelines.yml
`esy install` uses `.esy/source`, which is now also cached.
> Cache esy source which is used by esy install.

- src/Config_.re
- src/TranslateTypeDeclarations.re
Still need to activate based on version, once the version number where the corresponding bucklescript changes ship is known:  https://github.com/BuckleScript/bucklescript/pull/3785.
Check conversion of:
- Variants with inline records.
- Extensible variants with inline records.
- Exceptions with inline records.
For each case, boxed/unboxed and arrays/objects should match.
> Prepare for records represented as objects.

- src/Config_.re
- src/DeadCode.re
- src/GenType.re
- src/ModuleResolver.re
When a subproject is built from a root project, `bsb` does not create `lib/bs/.sourcedirs.json`.
This OR work around this limitation by finding the potential source dirs from the sources spec given in `bsconfig.json`.
NOTE: This still does not cover the case of dependencies which themselves use dependencies. For that to work, one needs to read the `"pkgs"` section of `.sourcedirs.json` in the bsb root directory.
This will be fixed when https://github.com/BuckleScript/bucklescript/commit/95bde3e69db7fa63b07c5d810d2ddf4e2231270a makes into a bucklescript release.
> Find source dirs from bsconfig.json.

- Changes.md
- examples/commonjs-react-example/package-lock.json
- examples/commonjs-react-example/package.json
- examples/flow-react-example/package.json
- examples/flow-react-example/src/Tuples.gen.js
- examples/flow-react-example/src/Tuples.re
- examples/flow-react-example/src/TypeExpansion.gen.js
- examples/typescript-react-example/package.json
- examples/typescript-react-example/src/AutoAnnotate.re
- examples/typescript-react-example/src/DeadCodeInterface.re
- examples/typescript-react-example/src/ReasonComponent.gen.tsx
- examples/typescript-react-example/src/Records.bs.js
- examples/typescript-react-example/src/Records.gen.tsx
- examples/typescript-react-example/src/Records.re
- examples/typescript-react-example/src/References.re
- examples/untyped-react-example/package-lock.json
- examples/untyped-react-example/package.json
- src/Converter.re
- src/EmitJs.re
- src/EmitType.re
- src/ExportModule.re
- src/GenTypeCommon.re
- src/NamedArgs.re
- src/TranslateStructure.re
- src/TranslateTypeDeclarations.re
- src/TranslateTypeExprFromTypes.re
- src/Translation.re
With bucklescript 7.x.y, apply conversion when a record field requires conversion.
> Fix record renaming conversion for bs 7.

- Changes.md
- README.md
- examples/typescript-react-example/bsconfig.json
- examples/typescript-react-example/use-some-library/bsconfig.json
- src/Config_.re
- src/ModuleResolver.re
Turn on support for dependent projects by default.
Document the feature.
> Dependent projects: turn on by default, and document the feature.

- Changes.md
- README.md
- examples/typescript-react-example/deadcode.txt
- examples/typescript-react-example/src/Records.bs.js
- examples/typescript-react-example/src/Records.gen.tsx
- examples/typescript-react-example/src/Records.re
- src/Annotation.re
- src/DeadType.re
- src/DeadValue.re
- src/EmitJs.re
- src/EmitType.re
- src/GenTypeMain.re
- src/TranslateCoreType.re
- src/TranslateSignature.re
- src/TranslateSignatureFromTypes.re
- src/TranslateStructure.re
- src/TranslateTypeDeclarations.re
- src/TranslateTypeExprFromTypes.re
- src/Translation.re
- src/TypeVars.re
If `@bs.as` is on a record field, the renamed name should be used in JS. No conversion is required.
See https://github.com/BuckleScript/bucklescript/issues/3979.
Docs should be updated to discourage the use of `@genType.as` for the same purpose (from bs 7.0.0. onwards).
> Support @bs.as to rename record fields.

- Changes.md
- examples/flow-react-example/src/AutoAnnotate.gen.js
- examples/flow-react-example/src/Component2.gen.js
- examples/flow-react-example/src/Types.gen.js
- examples/flow-react-example/src/Variants.bs.js
- examples/flow-react-example/src/Variants.gen.js
- examples/flow-react-example/src/Variants.re
- examples/flow-react-example/src/VariantsWithPayload.gen.js
- examples/flow-react-example/src/interop/ImportJsValue.gen.js
- examples/flow-react-example/src/nested/Nested.gen.js
- examples/typescript-react-example/src/AutoAnnotate.gen.tsx
- examples/typescript-react-example/src/ImportJsValue.gen.tsx
- examples/typescript-react-example/src/ReasonComponent.gen.tsx
- examples/typescript-react-example/src/Variants.bs.js
- examples/typescript-react-example/src/Variants.gen.tsx
- examples/typescript-react-example/src/Variants.re
- examples/typescript-react-example/src/VariantsWithPayload.gen.tsx
- examples/typescript-react-example/src/nested/Types.gen.tsx
- src/EmitType.re
Variants are emitted as `| x | y`, remove the leading `|`.
Also, Flow uses `?t`, so add parens: `? (foo | bar)`.
Fixes https://github.com/cristianoc/genType/issues/326.
> Fix issue when emitting optional variants.

- Changes.md
- examples/typescript-react-example/src/ExportWithRename.gen.tsx
- src/EmitJs.re
Fixes https://github.com/cristianoc/genType/issues/342
> In TS, emit import react when a react component is exported.

- Changes.md
- examples/typescript-react-example/package.json
- package.json
- src/DeadCode.re
- src/DeadCommon.re
If environment variable Whtelist=prefix is specified, only report on files having prefix in the path.
If environment variable Blacklist=prefix is specified, don't report on files having prefix in the path.
> [dce] Add support for whitelist and blacklist results.

- examples/typescript-react-example/deadcode.txt
- src/DeadCode.re
This also affects type analysis, to be looked into.
E.g. if a variant is only used in the implementation, then it's reported as unused in the interface.
But in that case, it can' be removed as implementation and interface need to be in sync.
However, it could be useful info: why are you exporting variant `A` if it's never used outside the implementation?
Likely, the answer is "it depends". E.g. if all variant cases are only used in the implementation, then it should probably be an abstract type.
> [DCE] Process interfaces in .re files even when .rei files exist.

- src/CodeItem.re
- src/EmitJs.re
- src/EmitText.re
- src/EmitType.re
- src/EmitType.rei
- src/TranslateTypeDeclarations.re
- src/Translation.re
Looks like EmitText.brackets is currently never used.
> Test acting on the results of coverage.

- README.md
Yesterday #436 added support for the new Bucklescript syntax. Some examples links in the README are now broken. This PR fixes them and some of the related wording.
> Added `.res/.resi` to the README and fixed broken links

- Changes.md
- examples/flow-react-example/src/Hooks.gen.js
- src/TranslateTypeExprFromTypes.re
Fixes https://github.com/reason-association/genType/issues/439
> Add missing support for `React.ref` (previously `React.Ref.t`).

- src/TranslateCoreType.re
- src/TranslateTypeExprFromTypes.re
Preparing to making `Js.t` optional in future when the compiler does it.
> Refactor: always check Js.t and object type together.

- Changes.md
- src/Config_.re
- src/Converter.re
- src/EmitJs.re
- src/EmitText.re
- src/EmitType.re
- src/ExportModule.re
- src/Runtime.re
- src/Runtime.rei
- src/TranslateSignature.re
- src/TranslateSignatureFromTypes.re
- src/TranslateStructure.re
- src/TranslateTypeDeclarations.re
- src/TranslateTypeExprFromTypes.re
- src/TypeEnv.re
There's a lot of code to deal with different runtime representations across versions of the compiler.
This disappears when supporting bs-platform 8.2 or newer.
> Remove legacy code for bs-platform before 8.2.

- Changes.md
- src/Config_.re
- src/EmitJs.re
Fixes https://github.com/rescript-association/genType/issues/521.
> Support "suffix" from `bsconfig.json` to specify the extension used by the compiler.
